// Pricing Plans Configuration
import { PricingPlan, CreditPack } from '@/types/subscription';

export const PRICING_PLANS: PricingPlan[] = [
    {
        id: 'free',
        tier: 'free',
        name: 'Free',
        description: 'Perfect for trying out the platform',
        monthlyPrice: 0,
        annualPrice: 0,
        features: [
            { id: 'projects', name: '1 Project', description: 'Create one website project', included: true, limit: 1 },
            { id: 'pages', name: '5 Pages', description: 'Up to 5 pages per project', included: true, limit: 5 },
            { id: 'ai-chat', name: 'AI Chat (Limited)', description: '50 AI messages/month', included: true, limit: 50 },
            { id: 'templates', name: 'Basic Templates', description: 'Access to starter templates', included: true },
            { id: 'export-html', name: 'HTML Export', description: 'Export as static HTML', included: true },
            { id: 'watermark', name: 'WebBuilder Watermark', description: 'Includes branding', included: true },
            { id: 'ai-components', name: 'AI Component Generation', description: 'Generate components with AI', included: false },
            { id: 'custom-domain', name: 'Custom Domain', description: 'Use your own domain', included: false },
            { id: 'collaboration', name: 'Team Collaboration', description: 'Work with team members', included: false },
        ],
        limits: {
            maxProjects: 1,
            maxPagesPerProject: 5,
            maxStorageMB: 100,
            maxBandwidthGB: 1,
            aiCreditsPerMonth: 50,
            aiComponentGeneration: false,
            aiImageGeneration: false,
            aiCodeExplanation: true,
            aiChatMessages: 50,
            aiAutoBuilder: false,
            customDomain: false,
            removeWatermark: false,
            exportCode: false,
            exportFormats: ['html'],
            teamMembers: 1,
            realTimeCollaboration: false,
            comments: false,
            versionHistory: 7,
            ecommerceEnabled: false,
            maxProducts: 0,
            transactionFeePercent: 0,
            customCode: false,
            apiAccess: false,
            webhooks: false,
            analytics: 'basic',
            prioritySupport: false,
            dedicatedManager: false,
            sla: false,
            whiteLabelEnabled: false,
        },
    },
    {
        id: 'starter',
        tier: 'starter',
        name: 'Starter',
        description: 'Great for personal projects and small sites',
        monthlyPrice: 12,
        annualPrice: 108, // $9/month billed annually
        features: [
            { id: 'projects', name: '5 Projects', description: 'Create up to 5 projects', included: true, limit: 5 },
            { id: 'pages', name: '20 Pages/Project', description: 'Up to 20 pages each', included: true, limit: 20 },
            { id: 'ai-chat', name: 'AI Chat (500/mo)', description: '500 AI messages/month', included: true, limit: 500 },
            { id: 'ai-components', name: 'AI Components', description: '50 component generations/mo', included: true, limit: 50 },
            { id: 'templates', name: 'Premium Templates', description: 'Access all templates', included: true },
            { id: 'export', name: 'HTML & React Export', description: 'Export in multiple formats', included: true },
            { id: 'storage', name: '1GB Storage', description: 'Asset storage', included: true },
            { id: 'watermark', name: 'Remove Watermark', description: 'No branding', included: true },
            { id: 'custom-domain', name: 'Custom Domain', description: 'Use your own domain', included: false },
            { id: 'collaboration', name: 'Team Collaboration', description: 'Work with team', included: false },
        ],
        limits: {
            maxProjects: 5,
            maxPagesPerProject: 20,
            maxStorageMB: 1024,
            maxBandwidthGB: 10,
            aiCreditsPerMonth: 500,
            aiComponentGeneration: true,
            aiImageGeneration: false,
            aiCodeExplanation: true,
            aiChatMessages: 500,
            aiAutoBuilder: false,
            customDomain: false,
            removeWatermark: true,
            exportCode: true,
            exportFormats: ['html', 'react'],
            teamMembers: 1,
            realTimeCollaboration: false,
            comments: false,
            versionHistory: 30,
            ecommerceEnabled: false,
            maxProducts: 0,
            transactionFeePercent: 0,
            customCode: true,
            apiAccess: false,
            webhooks: false,
            analytics: 'basic',
            prioritySupport: false,
            dedicatedManager: false,
            sla: false,
            whiteLabelEnabled: false,
        },
    },
    {
        id: 'pro',
        tier: 'pro',
        name: 'Pro',
        description: 'For professionals and growing businesses',
        monthlyPrice: 29,
        annualPrice: 290, // ~$24/month billed annually
        popular: true,
        badge: 'Most Popular',
        features: [
            { id: 'projects', name: 'Unlimited Projects', description: 'No project limits', included: true, limit: 'unlimited' },
            { id: 'pages', name: 'Unlimited Pages', description: 'No page limits', included: true, limit: 'unlimited' },
            { id: 'ai-chat', name: 'AI Chat (2000/mo)', description: '2000 AI messages/month', included: true, limit: 2000 },
            { id: 'ai-components', name: 'AI Components (200/mo)', description: '200 generations/month', included: true, limit: 200 },
            { id: 'ai-images', name: 'AI Image Generation', description: '50 images/month', included: true, limit: 50 },
            { id: 'ai-auto', name: 'AI Auto-Builder', description: 'Build entire pages with AI', included: true },
            { id: 'custom-domain', name: 'Custom Domain', description: 'Connect your domain', included: true },
            { id: 'storage', name: '10GB Storage', description: 'Asset storage', included: true },
            { id: 'collaboration', name: '3 Team Members', description: 'Collaborate with your team', included: true, limit: 3 },
            { id: 'analytics', name: 'Advanced Analytics', description: 'Detailed insights', included: true },
            { id: 'ecommerce', name: 'E-Commerce (5%)', description: 'Sell online', included: true },
        ],
        limits: {
            maxProjects: 'unlimited',
            maxPagesPerProject: 'unlimited',
            maxStorageMB: 10240,
            maxBandwidthGB: 100,
            aiCreditsPerMonth: 2000,
            aiComponentGeneration: true,
            aiImageGeneration: true,
            aiCodeExplanation: true,
            aiChatMessages: 2000,
            aiAutoBuilder: true,
            customDomain: true,
            removeWatermark: true,
            exportCode: true,
            exportFormats: ['html', 'react', 'vue'],
            teamMembers: 3,
            realTimeCollaboration: true,
            comments: true,
            versionHistory: 90,
            ecommerceEnabled: true,
            maxProducts: 100,
            transactionFeePercent: 5,
            customCode: true,
            apiAccess: true,
            webhooks: true,
            analytics: 'advanced',
            prioritySupport: true,
            dedicatedManager: false,
            sla: false,
            whiteLabelEnabled: false,
        },
    },
    {
        id: 'business',
        tier: 'business',
        name: 'Business',
        description: 'For teams and agencies with advanced needs',
        monthlyPrice: 79,
        annualPrice: 790, // ~$66/month billed annually
        features: [
            { id: 'everything-pro', name: 'Everything in Pro', description: 'All Pro features included', included: true },
            { id: 'ai-unlimited', name: 'Unlimited AI', description: 'No AI usage limits', included: true, limit: 'unlimited' },
            { id: 'team', name: '10 Team Members', description: 'Larger team collaboration', included: true, limit: 10 },
            { id: 'storage', name: '100GB Storage', description: 'Enterprise storage', included: true },
            { id: 'white-label', name: 'White Label', description: 'Your branding', included: true },
            { id: 'ecommerce', name: 'E-Commerce (2%)', description: 'Lower transaction fees', included: true },
            { id: 'api', name: 'Full API Access', description: 'Build integrations', included: true },
            { id: 'support', name: 'Priority Support', description: '24/7 priority support', included: true },
            { id: 'analytics', name: 'Enterprise Analytics', description: 'Full insights suite', included: true },
        ],
        limits: {
            maxProjects: 'unlimited',
            maxPagesPerProject: 'unlimited',
            maxStorageMB: 102400,
            maxBandwidthGB: 500,
            aiCreditsPerMonth: 'unlimited',
            aiComponentGeneration: true,
            aiImageGeneration: true,
            aiCodeExplanation: true,
            aiChatMessages: 'unlimited',
            aiAutoBuilder: true,
            customDomain: true,
            removeWatermark: true,
            exportCode: true,
            exportFormats: ['html', 'react', 'vue', 'nextjs'],
            teamMembers: 10,
            realTimeCollaboration: true,
            comments: true,
            versionHistory: 365,
            ecommerceEnabled: true,
            maxProducts: 1000,
            transactionFeePercent: 2,
            customCode: true,
            apiAccess: true,
            webhooks: true,
            analytics: 'enterprise',
            prioritySupport: true,
            dedicatedManager: false,
            sla: true,
            whiteLabelEnabled: true,
        },
    },
    {
        id: 'enterprise',
        tier: 'enterprise',
        name: 'Enterprise',
        description: 'Custom solutions for large organizations',
        monthlyPrice: 0, // Custom pricing
        annualPrice: 0,
        badge: 'Custom Pricing',
        features: [
            { id: 'everything', name: 'Everything in Business', description: 'All features included', included: true },
            { id: 'team', name: 'Unlimited Team', description: 'No member limits', included: true, limit: 'unlimited' },
            { id: 'storage', name: 'Unlimited Storage', description: 'No storage limits', included: true, limit: 'unlimited' },
            { id: 'ecommerce', name: 'E-Commerce (0%)', description: 'No transaction fees', included: true },
            { id: 'sso', name: 'SSO & SAML', description: 'Enterprise authentication', included: true },
            { id: 'manager', name: 'Dedicated Manager', description: 'Personal account manager', included: true },
            { id: 'sla', name: '99.99% SLA', description: 'Enterprise uptime guarantee', included: true },
            { id: 'custom', name: 'Custom Integrations', description: 'Tailored solutions', included: true },
            { id: 'training', name: 'Onboarding & Training', description: 'Full team training', included: true },
        ],
        limits: {
            maxProjects: 'unlimited',
            maxPagesPerProject: 'unlimited',
            maxStorageMB: 'unlimited',
            maxBandwidthGB: 'unlimited',
            aiCreditsPerMonth: 'unlimited',
            aiComponentGeneration: true,
            aiImageGeneration: true,
            aiCodeExplanation: true,
            aiChatMessages: 'unlimited',
            aiAutoBuilder: true,
            customDomain: true,
            removeWatermark: true,
            exportCode: true,
            exportFormats: ['html', 'react', 'vue', 'nextjs'],
            teamMembers: 'unlimited' as any,
            realTimeCollaboration: true,
            comments: true,
            versionHistory: 'unlimited' as any,
            ecommerceEnabled: true,
            maxProducts: 'unlimited' as any,
            transactionFeePercent: 0,
            customCode: true,
            apiAccess: true,
            webhooks: true,
            analytics: 'enterprise',
            prioritySupport: true,
            dedicatedManager: true,
            sla: true,
            whiteLabelEnabled: true,
        },
    },
];

export const CREDIT_PACKS: CreditPack[] = [
    { id: 'credits-100', name: 'Starter Pack', credits: 100, price: 5 },
    { id: 'credits-500', name: 'Creator Pack', credits: 500, price: 20, bonusCredits: 50, popular: true },
    { id: 'credits-1000', name: 'Pro Pack', credits: 1000, price: 35, bonusCredits: 150 },
    { id: 'credits-5000', name: 'Agency Pack', credits: 5000, price: 150, bonusCredits: 1000 },
];

export const AFFILIATE_TIERS = {
    bronze: { minReferrals: 0, commissionPercent: 20 },
    silver: { minReferrals: 10, commissionPercent: 25 },
    gold: { minReferrals: 50, commissionPercent: 30 },
    platinum: { minReferrals: 200, commissionPercent: 35 },
};

export function getPlanById(planId: string): PricingPlan | undefined {
    return PRICING_PLANS.find(p => p.id === planId);
}

export function getPlanByTier(tier: string): PricingPlan | undefined {
    return PRICING_PLANS.find(p => p.tier === tier);
}

export function calculateAnnualSavings(plan: PricingPlan): number {
    const monthlyTotal = plan.monthlyPrice * 12;
    return monthlyTotal - plan.annualPrice;
}

export function calculateAnnualSavingsPercent(plan: PricingPlan): number {
    if (plan.monthlyPrice === 0) return 0;
    const savings = calculateAnnualSavings(plan);
    return Math.round((savings / (plan.monthlyPrice * 12)) * 100);
}
